version: 2

sources:
  - name: FEC
    database: RAW
    schema: FEC

    tables:
      - name: CANDIDATE_COMMITTEE_LINK
        columns:
          - name: CAND_ID

      - name: CANDIDATE_MASTER
        columns:
          - name:CAND_ID
            tests:
              - unique        
      - name: COMMITTEE_MASTER
        columns:
          - name: CMTE_ID
            tests:
              - unique        
      - name: CONTRIBUTIONS_TO_CANDIDATES
        columns:
          - name: TRAN_ID
            tests:
              - unique

      - name: DATES
        columns:
          - name: DATEKEY
            tests:
              - unique
      - name: INDIVIDUAL_CONTRIBUTIONS
        columns:
          - name: TRAN_ID
            tests:
              - unique      
      - name: OPERATING_EXPENSES
        columns:
          - name: SUB_ID
            tests:
              - unique                                                  
      - name: PAC_SUMMARY
        columns:
          - name: CMTE_ID
            tests:
              - unique  
                  
      - name: ZIP_CODES
        columns:
          - name: ZIPCODE
            tests:
              - unique  
                                    